name: Generate Contribution Snake
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake svg
        uses: Platane/snk@master
        with:
          github_user_name: lifany-jia
          svg_out_path: github-contribution-grid-snake.svg

      - name: Commit & Push snake svg to output branch
        uses: ad-m/github-push-action@master
        with:
          branch: output
          directory: .
          github_token: ${{ secrets.GITHUB_TOKEN }}
